import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Context
import { ThemeProvider } from "@/context/ThemeContext";

// Components
import Header from "@/components/header";
import Footer from "@/components/footer";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import ThemeToggle from "@/components/ThemeToggle";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
(function() {
  try {
    var stored = localStorage.getItem('theme');
    var isDark = stored !== 'light';
    if (isDark) document.documentElement.classList.add('dark');
    else document.documentElement.classList.remove('dark');
  } catch (e) {}
})();
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={JetBrainsMono.variable}>
        <ThemeProvider>
          <BackgroundAnimation />
          <Header />
          {children}
          <Footer />
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
