import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Context
import { ThemeProvider } from "@/context/ThemeContext";

// Components
import Header from "@/components/header";
import Footer from "@/components/footer";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import ThemeToggle from "@/components/ThemeToggle";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <ThemeProvider>
          <BackgroundAnimation />
          <Header />
          {children}
          <Footer />
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
